---
title: 'Homework #5'
author: "Charlotte Uden"
date: "9/26/2018"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1

```{r,echo=TRUE}
library(dplyr)
data(iris)
glimpse(iris)
# There are 5 variables and 150 observations in this data set. 
```

2 

```{r,echo=TRUE}
iris1 <- filter(iris, Species %in% c("virginica","versicolor"), Sepal.Length > 6, Sepal.Width > 2.5)
glimpse(iris1)

# there are 17 observations and 5 variables
```

3

```{r,echo=TRUE}
iris2 <- select(iris1, Species, Sepal.Length, Sepal.Width)
glimpse(iris2)
# there are 17 observations and 3 variables. 
```

4

```{r,echo=TRUE}
iris3 <- arrange(iris2, desc(Sepal.Length))
head(iris3)
```

5

```{r,echo=TRUE}
iris4 <- mutate(iris3, Sepal.Area=Sepal.Length*Sepal.Width)
glimpse(iris4)
# there are 17 observations and 4 variables
```

6

```{r,echo=TRUE}
iris5 <- summarize(iris4, mean(Sepal.Length), mean(Sepal.Width), number=n())
print(iris5)
```

7

```{r,echo=TRUE}
iris6 <- group_by(iris4, Species)
iris6 <- summarize(iris6, mean(Sepal.Length), mean(Sepal.Width), number=n())
print(iris6)
```

8

```{r,echo=TRUE}
iris %>%
  filter(Species %in% c("virginica","versicolor"), Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(Species, Sepal.Length, Sepal.Width) %>%
  arrange(desc(Sepal.Length)) %>%
  mutate(Sepal.Area=Sepal.Length*Sepal.Width) %>%
  group_by(Species)%>%
  summarize(mean(Sepal.Length), mean(Sepal.Width), number=n())
  
  #cannot use this code (only gives you 25): filter(species==c("virginica","versicolor")
```
